
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'


stages:
  - build

build:
  stage: build
  image: martinkylian/ci
  environment:
    name: $CI_COMMIT_REF_SLUG
  script:
    - . <(printenv CONFIG | grep -v '^#\|^$\|^\s+$' | sed 's/^/export /')
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker-compose build --pull
    - docker-compose push
    - docker logout $CI_REGISTRY
